### ISSUE TITLE
Add a LICENSE?

### ISSUE THREAD

**Issue by HackYardo** [pbatr/Civ4-Reimagined#7]
Hello there, 
  Thank you for the little but outstanding Civ4 mod! 
  As an open source project, if no License, nobody can use the source code. Details: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository
  Will you add a License? The Civ4 Reimagined mod uses some other mods and resources, their licenses make sense... Sometimes it is pretty hard to add a proper license...

**Comment by pbatr** [comment]
Hi HackYardo,
thank you for your comment. I added the licence file.

**Comment by HackYardo** [comment]
Hi, pbatr.
I find a few questions: 
1. there is an `Info/GNU Public License.rtf`(**GPL3**), so **MIT** LICENSE can not be used, you can only use GPL3 because of GPL3.
2. I played 5 games of version 2.0 yesterday, and they all **crashed at 70`100 turns**. What should I do to fix it?

**Comment by pbatr** [comment]
Hi HackYardo,

oh good point I didn't see the license of BUG mod. I updated it accordingly. Regarding the crash I will try to reproduce it. If you have a savegame for me one turn before the crash, you could speed up the process. And you are also right about mod structure inside the zip. Will probably update it later. Right now it should all go into `Civ4 Reimagined`.

**Comment by pbatr** [comment]
Nevermind, could reproduce the crash. Fix will come soon.

**Comment by HackYardo** [comment]
I tried to reproduced it yesterday, but the game continued over 200 turns and not crashed yet, so it perhaps was a win11 insider preview update issue... How ever, you could reproduced the crashed...
